# Generated by Django 5.0.4 on 2024-04-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('imageurl', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
