# Generated by Django 5.0.4 on 2024-04-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cartId', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('imageurl', models.CharField(max_length=500)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
