# Generated by Django 5.0.4 on 2024-05-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_imgid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imgid',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
